[package]
name = "zed_nextflow"
version = "0.4.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/nextflow.rs"
crate-type = ["cdylib"]

[dependencies]
log = "0.4.27"
zed_extension_api = "0.1.0"
